### ISSUE TITLE
ulmapi.de not working

### ISSUE THREAD

**Issue by fnogatz** [UlmApi/ulmapi.github.com#17]
![screenshot from 2015-05-21 00 40 31](https://cloud.githubusercontent.com/assets/881988/7738179/0502de28-ff52-11e4-9a2f-c88dd67b0818.png)

http://www.ulmapi.de/ is working, http://ulmapi.de/ not.

**Comment by namnatulco** [comment]
Note to self: figure out how to fix this permanently.

**Comment by fnogatz** [comment]
Is this still a thing?

**Comment by namnatulco** [comment]
I just checked the config; right now, `ulmapi.de` is directed at an IP with an A record, and `www.ulmapi.de` is directed at `ulmapi.github.io` with a CNAME. For some (probably logical, but unknown to me) reason, I can't configure a CNAME for `ulmapi.de`. I don't know what the elegant solution is, but it seems to work, I haven't changed the config since that comment.

**Comment by fnogatz** [comment]
Closing as it is working now. Feel free to open again, if you want to leave it as a reminder.
